/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package design;

import java.util.Iterator;

import javax.swing.table.DefaultTableModel;

import BE.Customer;
import BE.Ingredient;
import plurality.Customers;
import plurality.Employees;
import plurality.Ingredients;

@SuppressWarnings("serial")
public class ManagerHome extends javax.swing.JFrame {

    /**
     * Creates new form Demo
     */
	public static DefaultTableModel tblModel;
    public ManagerHome() {
        initComponents();
        initTableEmployee();
        loadEmployee();
        initTableIngredient();
        loadIgredient();
        initTableCustomer();
        loadCustomer();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        new javax.swing.JScrollBar();
        jPanel7 = new javax.swing.JPanel();
        manager = new javax.swing.JLabel();
        text_manager = new javax.swing.JLabel();
        lbreturn = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTabbleEmployee = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbEmployee = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        lbUpdate = new javax.swing.JLabel();
        lbAdd = new javax.swing.JLabel();
        lbDelete = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbProduct = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        inventory = new javax.swing.JLabel();
        thung = new javax.swing.JLabel();
        price = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbCustomer = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        point = new javax.swing.JLabel();
        hcmcity = new javax.swing.JLabel();
        member = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel7.setBackground(new java.awt.Color(139, 217, 189));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manager.setIcon(new javax.swing.ImageIcon("D:/eclipse/Github/Cafe_Manager/Cafe_Manager_BE/src/design/Icon/icons8-manager-100.png")); // NOI18N
        manager.setPreferredSize(new java.awt.Dimension(110, 110));
        jPanel7.add(manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 11, -1, -1));

        text_manager.setFont(new java.awt.Font("FreeMono", 1, 24)); // NOI18N
        text_manager.setForeground(new java.awt.Color(102, 102, 255));
        text_manager.setText("MANAGER");
        jPanel7.add(text_manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 127, -1, -1));

        lbreturn.setIcon(new javax.swing.ImageIcon("D:/eclipse/Github/Cafe_Manager/Cafe_Manager_BE/src/design/Icon/icons8-logout-50.png")); // NOI18N
        jPanel7.add(lbreturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 390, 79, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon("D:/eclipse/Github/Cafe_Manager/Cafe_Manager_BE/src/design/Icon/icons8-coffee-100.png")); // NOI18N
        jPanel7.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(64, 217, -1, -1));

        jTabbleEmployee.setBackground(new java.awt.Color(198, 236, 233));
        jTabbleEmployee.setForeground(new java.awt.Color(198, 236, 233));

        jPanel1.setBackground(new java.awt.Color(198, 236, 233));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jScrollPane1.setViewportView(tbEmployee);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 68, 729, 268));

        jLabel4.setFont(new java.awt.Font("FreeMono", 3, 24)); // NOI18N
        jLabel4.setText("Employee's Information");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 18, -1, -1));

        lbUpdate.setIcon(new javax.swing.ImageIcon("D:/eclipse/Github/Cafe_Manager/Cafe_Manager_BE/src/design/Icon/icons8-update-48.png")); // NOI18N
        lbUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbUpdateMouseClicked(evt);
            }
        });
        jPanel1.add(lbUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 360, 65, 58));

        lbAdd.setIcon(new javax.swing.ImageIcon("D:/eclipse/Github/Cafe_Manager/Cafe_Manager_BE/src/design/Icon/icons8-add-48.png")); // NOI18N
        lbAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAddMouseClicked(evt);
            }
        });
        jPanel1.add(lbAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 360, 59, 59));

        lbDelete.setIcon(new javax.swing.ImageIcon("D:/eclipse/Github/Cafe_Manager/Cafe_Manager_BE/src/design/Icon/icons8-delete-48.png")); // NOI18N
        lbDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDeleteMouseClicked(evt);
            }
        });
        jPanel1.add(lbDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 354, -1, 65));

        jTabbleEmployee.addTab("Statistic Employee", jPanel1);

        jPanel3.setBackground(new java.awt.Color(198, 236, 233));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setViewportView(tbProduct);
        if (tbProduct.getColumnModel().getColumnCount() > 0) {
            tbProduct.getColumnModel().getColumn(0).setPreferredWidth(20);
            tbProduct.getColumnModel().getColumn(1).setPreferredWidth(50);
            tbProduct.getColumnModel().getColumn(5).setPreferredWidth(20);
        }

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 742, 266));

        jLabel7.setFont(new java.awt.Font("FreeMono", 3, 24)); // NOI18N
        jLabel7.setText("Product's Information");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(216, 27, -1, -1));

        inventory.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        inventory.setText("Inventory <3");
        inventory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryMouseClicked(evt);
            }
        });
        jPanel3.add(inventory, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 390, -1, -1));

        thung.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        thung.setText("Thung");
        thung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                thungMouseClicked(evt);
            }
        });
        jPanel3.add(thung, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 390, -1, -1));

        price.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        price.setText("Price >100K");
        price.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                priceMouseClicked(evt);
            }
        });
        jPanel3.add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, -1, -1));

        jTabbleEmployee.addTab("Statistic Product", jPanel3);

        jPanel2.setBackground(new java.awt.Color(198, 236, 233));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane3.setViewportView(tbCustomer);

        jPanel2.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 77, 742, 273));

        jLabel5.setFont(new java.awt.Font("FreeMono", 3, 24)); // NOI18N
        jLabel5.setText("Customer's Information");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 27, -1, -1));

        point.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        point.setText("Point >=100");
        point.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pointMouseClicked(evt);
            }
        });
        jPanel2.add(point, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, -1, -1));

        hcmcity.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        hcmcity.setText("HCM city");
        hcmcity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hcmcityMouseClicked(evt);
            }
        });
        jPanel2.add(hcmcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 390, -1, -1));

        member.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        member.setText("Gold member");
        member.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                memberMouseClicked(evt);
            }
        });
        jPanel2.add(member, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 390, -1, -1));

        jTabbleEmployee.addTab("Statistic Customer", jPanel2);

        jPanel7.add(jTabbleEmployee, new org.netbeans.lib.awtextra.AbsoluteConstraints(226, 0, -1, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(983, 507));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void pointMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pointMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_pointMouseClicked

    private void hcmcityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hcmcityMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_hcmcityMouseClicked

    private void memberMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_memberMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_memberMouseClicked

    private void inventoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_inventoryMouseClicked

    private void thungMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_thungMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_thungMouseClicked

    private void priceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_priceMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_priceMouseClicked

    private void lbAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbAddMouseClicked

    private void lbUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbUpdateMouseClicked

    private void lbDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lbDeleteMouseClicked

    /**
     * @param args the command line arguments
     */
    public void initTableEmployee() {
    	tblModel = new DefaultTableModel();
    	tblModel.setColumnIdentifiers(new String[] {"STT", "ID", "Name", "Position", "Bonus", "Minus", "Coffecient", "Hour", "Salary"});
    	tbEmployee.setModel(tblModel);
    }
    public void loadEmployee() {
    	Employees e = new Employees();
    	e.printSQL();
    	int j = 1;
    	tblModel.setRowCount(0);
    	for(int i = 0; i<e.size(); i++) {
    		Object[] row = new Object[] {
    			j++,e.elementAt(i).getId(),e.elementAt(i).getSurname()+" "+e.elementAt(i).getName(),e.elementAt(i).getPosition(),e.elementAt(i).getBonus(),e.elementAt(i).getMinus(),e.elementAt(i).getCoefficients(),e.elementAt(i).getWorking_hour(),e.elementAt(i).getSalary()
    		};
    		tblModel.addRow(row);
    	}
    	tblModel.fireTableDataChanged();
    }
    public void initTableIngredient() {
    	tblModel = new DefaultTableModel();
    	tblModel.setColumnIdentifiers(new String[] {"STT", "ID", "Name", "Quantities", "Price", "Unit", "Date input", "Inventory"});
    	tbProduct.setModel(tblModel);
    }
    public void loadIgredient() {
    	Ingredients in = new Ingredients();
    	in.printSQL();
    	int j = 1;
    	Iterator<Ingredient> it = in.iterator();
    	tblModel.setRowCount(0);
    	while(it.hasNext()) {
    		Ingredient i = new Ingredient();
    		i = it.next();
    		Object[] row = new Object[] {
    			j++,i.getId(),i.getName(),i.getAmount(),i.getPrice(),i.getUnit(),i.getDay()+"/"+i.getMonth()+"/"+i.getYear(),i.getInventory()	
    		};
    		tblModel.addRow(row);
    	}
    	tblModel.fireTableDataChanged();
    }
    public void initTableCustomer() {
    	tblModel = new DefaultTableModel();
    	tblModel.setColumnIdentifiers(new String[] {"STT", "ID", "Name", "Gender", "Birthday", "Address", "Point", "Member", "Phone"});
    	tbCustomer.setModel(tblModel);
    }
    public void loadCustomer() {
    	Customers c = new Customers();
    	c.getData();
    	int j = 1;
    	Iterator<Customer> it = c.iterator();
    	tblModel.setRowCount(0);
    	while(it.hasNext()) {
    		Customer cm = new Customer();
    		cm = it.next();
    		Object[] row = new Object[] {
    				j++,cm.getId(),cm.getSurname()+" "+cm.getName(),cm.getGender(),cm.getDay()+"/"+cm.getMonth()+"/"+cm.getYear(),cm.getAddress(),cm.getPoint(),cm.getMember(),cm.getPhone()
    		};
    		tblModel.addRow(row);
    	}
    	tblModel.fireTableDataChanged();
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManagerHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManagerHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hcmcity;
    private javax.swing.JLabel inventory;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbleEmployee;
    private javax.swing.JLabel lbAdd;
    private javax.swing.JLabel lbDelete;
    private javax.swing.JLabel lbUpdate;
    private javax.swing.JLabel lbreturn;
    private javax.swing.JLabel manager;
    private javax.swing.JLabel member;
    private javax.swing.JLabel point;
    private javax.swing.JLabel price;
    private javax.swing.JTable tbCustomer;
    private javax.swing.JTable tbEmployee;
    private javax.swing.JTable tbProduct;
    private javax.swing.JLabel text_manager;
    private javax.swing.JLabel thung;
    // End of variables declaration//GEN-END:variables
}
